# Generated by Django 5.0.6 on 2026-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0064_samaj_person_guj_first_name_person_guj_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
