# Generated by Django 5.0.6 on 2026-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0065_alter_person_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentchildrelation',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
