# Generated by Django 5.0.6 on 2026-02-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0066_parentchildrelation_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='surname',
            name='samaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surnames', to='parivar.samaj'),
        ),
        migrations.AlterField(
            model_name='surname',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='surname',
            unique_together={('name', 'samaj')},
        ),
    ]
