# Generated by Django 5.0.6 on 2026-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0067_surname_samaj_alter_surname_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samaj',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard')], default='free'),
        ),
    ]
