# Generated by Django 5.0.6 on 2026-02-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0068_samaj_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateperson',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translateperson', to='parivar.person'),
        ),
    ]
