# Generated by Django 5.0.6 on 2026-02-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0069_alter_translateperson_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='country_flags/'),
        ),
    ]
