# Generated by Django 5.0.6 on 2026-02-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0070_country_flag'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['is_active'], name='parivar_dis_is_acti_734f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['created_at'], name='parivar_dis_created_c7d725_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelation',
            index=models.Index(fields=['parent'], name='parivar_par_parent__7a6094_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelation',
            index=models.Index(fields=['child'], name='parivar_par_child_i_2f836c_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelation',
            index=models.Index(fields=['is_deleted'], name='parivar_par_is_dele_8cd752_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelation',
            index=models.Index(fields=['created'], name='parivar_par_created_ef7b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['samaj'], name='parivar_per_samaj_i_27ed2f_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['city'], name='parivar_per_city_id_9458df_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['state'], name='parivar_per_state_i_e6135a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_deleted'], name='parivar_per_is_dele_3409a5_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_time'], name='parivar_per_created_cf2bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['surname'], name='parivar_per_surname_b42f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['flag_show'], name='parivar_per_flag_sh_199634_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['mobile_number1'], name='parivar_per_mobile__ede88f_idx'),
        ),
        migrations.AddIndex(
            model_name='taluka',
            index=models.Index(fields=['district'], name='parivar_tal_distric_cf1bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='taluka',
            index=models.Index(fields=['is_active'], name='parivar_tal_is_acti_8e134a_idx'),
        ),
        migrations.AddIndex(
            model_name='taluka',
            index=models.Index(fields=['created_at'], name='parivar_tal_created_301c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='translateperson',
            index=models.Index(fields=['language'], name='parivar_tra_languag_e5c7a2_idx'),
        ),
        migrations.AddIndex(
            model_name='translateperson',
            index=models.Index(fields=['is_deleted'], name='parivar_tra_is_dele_81935b_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['taluka'], name='parivar_vil_taluka__506b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['is_active'], name='parivar_vil_is_acti_7829a2_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['created_at'], name='parivar_vil_created_6fa3ab_idx'),
        ),
    ]
