# Generated by Django 5.0.6 on 2026-02-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0071_district_parivar_dis_is_acti_734f6c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adssetting',
            name='samaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads_settings', to='parivar.samaj'),
        ),
    ]
