# Generated by Django 5.0.6 on 2026-02-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0072_adssetting_samaj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adssetting',
            name='samaj',
        ),
        migrations.AddField(
            model_name='adssetting',
            name='samaj',
            field=models.ManyToManyField(blank=True, related_name='ads_settings', to='parivar.samaj'),
        ),
    ]
