# Generated by Django 5.0.6 on 2026-02-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0073_remove_adssetting_samaj_adssetting_samaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='randombanner',
            name='samaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='random_banners', to='parivar.samaj'),
        ),
    ]
