# Generated by Django 5.0.6 on 2026-03-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0075_country_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_number1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_number2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
