# Generated by Django 5.0.6 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parivar", "0076_alter_person_mobile_number1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="mobile_number_length",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]

