# Generated by Django 5.0.6 on 2026-02-26 10:05

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_personplayerid_updated_at'),
        ('parivar', '0071_district_parivar_dis_is_acti_734f6c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expire_date'], name='notificatio_expire__f24ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_event'], name='notificatio_is_even_7f791d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=django.contrib.postgres.indexes.GinIndex(fields=['filter'], name='notificatio_filter_0d973a_gin'),
        ),
    ]
